# Generated by Django 3.2.9 on 2022-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='original_image_url',
            new_name='original_url',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='image_url',
            new_name='resrc_url',
        ),
        migrations.AddField(
            model_name='question',
            name='offline_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='resrc_type',
            field=models.CharField(choices=[('image/jpeg', 'Img'), ('audio/mp3', 'Mp3')], default=None, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='reveal_image_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='system_check',
            field=models.CharField(choices=[('Valid', 'valid'), ('Invalid', 'invalid'), ('Duplicate', 'duplicate'), ('Profanity', 'Profanity')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
