# Generated by Django 3.2.9 on 2022-03-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220308_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('PEOPLE', 'People'), ('POLITICS', 'Politics'), ('BUSINESS & TECH', 'Business & Tech'), ('CARS', 'Cars'), ('ART', 'Art'), ('TRUE OR FALSE', 'True_or_false'), ('I SPY', 'I_spy'), ("WHO's THIS", "Who's this"), ('MATH', 'Math'), ('SCIENCE', 'Science'), ('FOOD', 'Food'), ('HISTORY', 'History'), ('BOOKS', 'Books'), ('LIFESTYLE', 'Lifestyle'), ('MUSIC', 'Music'), ('WORD JAM', 'Word_jam'), ('GEOGRAPHY', 'Geography'), ('SPORTS', 'Sports'), ('ENTERTAINMENT', 'Entertainment'), ('HANX MOVIES', 'Hanx Movies')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
