# Generated by Django 3.2.9 on 2022-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220329_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='images_x',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
